In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

arr

In [28]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a=np.array([1,2,3,4])

In [33]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [34]:
a

array([1, 2, 3, 4])

In [36]:
randarr=np.arange(10)

In [37]:
randarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
randarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
randarr.argmin()

0

In [44]:
randarr.shape


(10,)

In [45]:
randarr.dtype

dtype('int32')

In [46]:
arr=np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[9]

9

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [58]:
print(arr[-1:-6])

[]


In [60]:
_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [63]:
_2d[1][2]

30

In [64]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
prac=np.arange(50).reshape(5,10)

In [5]:
prac

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [6]:
prac[1:4,2:3]

array([[12],
       [22],
       [32]])

In [7]:
prac[2:3,1:4]

array([[21, 22, 23]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.ones(10)+5

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [13]:
np.arange(0,52,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(1)

array([0.86972558])

In [22]:
np.random.randn(25)

array([-0.2475855 , -0.82066514, -2.68649232,  0.63909964,  1.36184874,
        0.30302279, -0.47678593,  2.90223143, -1.14589552,  1.58552053,
        1.09969723,  0.40322003,  1.34838318, -2.01498402,  1.33634742,
        1.39939723,  0.31170328, -1.03589659, -0.93985888,  1.54515989,
        1.11420072, -0.02553202,  0.09784174, -0.19939264,  1.52602023])

In [26]:
np.random.randint(0,100,25)

array([12, 40, 87, 80, 17, 20, 65, 39, 22, 54, 63, 18, 38, 74, 31, 44, 85,
       25, 92, 70, 97, 35, 88, 91, 12])